### ISSUE TITLE
Should i use a SPA ?

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#1]
The soundcore module will be a Single Page Application.
Now my question is should I use SPA for AnimeCore, MangaCore?

But it will be a lot of work and pointless refractoring. Not to mention the countless [warnings](https://github.com/facebook/create-react-app/issues/11174) that i have to face

**Comment by Avasam** [comment]
You don't have to use Create-React-App to begin with for a React application. There's other alternatives (including just setting it up yourself).
If you still want to go that route, there's a workaround: https://github.com/facebook/create-react-app/issues/11174#issuecomment-979449264

**Comment by baseplate-admin** [comment]
Hi there,

Thanks for responding. But in that sense, Isn't it better to Just use blitz.js( full stack react framework ). Cause in current setup django will Just serve json.

**Comment by baseplate-admin** [comment]
But I still am rethinking the approach. In my opinion this software can be the next Kissanime. Only if i had some funds ( i am kinda against advertising ).
