### ISSUE TITLE
Project needs a logo.

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#101]
As the title goes. Currently we are using bulma placeholder. But as the time progresses, i think it would be better to have our own logo

**Comment by AKindWorld** [comment]
Hi hi!

Having a logo is an extremely good idea; however, there are several factors that to decide on before finalizing on one:

1. The entire project's color/design schemes (all the way from the main UI to the icon choices) is very much dependent on the logo, or vice-versa. Example: rounded icons vs sharp icons, neutral colors vs vivid, based off an existing design system or one created from scratch, etc.
Although logos & colors can be changed anytime so it isn't that big of an issue; just ends up being more work.

2. The type of logo you'd want ~ whether just a simple shaped, or a more dynamic one. Also, the base of the entire project, i.e. what the project is based on; for example- most anime streaming sites use either a character based logo (zoro), or just simple styled text (pahe, 9). Others may also rely on similar moe concepts (nyaa). 
So, yup, it depends on which type you'd want & if you've already thought of a sketch/prototype.

These are just my opinions~! If you'd like to, then you can always base off a simple one for now, and change stuff during release, when the project's image is clearly set. Or, you can also base the entire project's design scheme off of the final logo, in which case, as you said, the project immediately needs one.

thanks for reading~

**Comment by baseplate-admin** [comment]
Hi there,

Thanks for taking an interest in this project.

1. The project's icon scheme is fully based on [ionicons](https://ionic.io/ionicons). I am using black and white icons but i plan on making color adjustments to the icons. For me i think the best choice would be a vivid logo. But if i find a good logo i am in for doing a full color change.

2. I think text based logo is better for this project. As someone who enjoys [Genshin Impact](https://genshin.mihoyo.com/en/gift), i kinda like that type of logo. I am all in for simplicity. But i dont mind a good artwork.

**Comment by AKindWorld** [comment]
I see, I see.

1. IonIcons is an amazing icons source; although, the choice still depends on which icons you're using - rounded or sharp. From the Readme preview, I think it's the former? or maybe... I can just clone the repo and see it myself. 

2. aha, yup! I understand the type of logo you're talking about (fellow Genshin enjoyer!). Text based logos are much easier to make, and if done right, look great as well. I'm curious though, what is the final name of the project? Core...? or do you wanna include something else? 
If you do wanna include any art later on, that can always be done without worrying too much about the rest of the design. 

I think that's a good decision overall. And, if you'd want, I may be able to help with the design & logo as well; I'd love to be able to contribute to this project. 

anyways, good day to you~!

**Comment by baseplate-admin** [comment]
1, Why don't you take a look at some screenshots ? The UI is very round-ish. But ionicons doesn't offer many round icons. ( _do you know about an icon pack that offers rounded icons ?_ )  

<details>
<summary>
Login Page
</summary>

![login](https://user-images.githubusercontent.com/61817579/160042995-28d41c99-ed3a-4486-9870-7620f2d38cd2.jpg)

</details>

<details>
<summary>
Register page
</summary>

![register](https://user-images.githubusercontent.com/61817579/160043183-51512814-7046-4e62-9056-f46daef1d8b1.jpg)

</details>

<details>
<summary>
Edit Info Page
</summary>

![edit info](https://user-images.githubusercontent.com/61817579/160043216-4fd806ac-7b0e-4692-a653-63bb389669c6.jpg)

</details>

<details>
<summary>
Home Page
</summary>

![frontpage](https://user-images.githubusercontent.com/61817579/160043243-5dcd83d2-43f8-4b5c-b715-4752c5b69f47.jpg)

</details>

<details>
<summary>
Anime Info Page
</summary>


![inex](https://user-images.githubusercontent.com/61817579/160043266-ec3a4ea0-aa54-4c69-a6d9-972582b8da8e.jpg)

</details>

2. So the naming system came like this. I had a [Anker Soundcore](https://www.amazon.com/Soundcore-Cancelling-Headphones-Wireless-Bluetooth/dp/B07NM3RSRQ) and i based my [other project](https://github.com/baseplate-admin/soundcore) off of this name. Now because i cant name anything good, i thought animecore would sound cool. ( The repo was originally named animecore. https://github.com/baseplate-admin/AnimeCore/ ). And then i thought since i will eventually merge [Soundcore](https://github.com/baseplate-admin/soundcore) into this repository. It would be better to name this repo CoreProject and Add core after everything ( eg: Anime"Core", Sound"Core" ). But if you think that this project needs a better name or something feel free to let me know :D . This software is very alpha, and you can change the name of this project just by changing it [here](https://github.com/baseplate-admin/CoreProject/blob/9d3e79cff5a914fd1a164e23e5a18fb1da5ff257/AnimeCore/frontend/src/lib/constants/frontend/project.ts#L1)

**Comment by AKindWorld** [comment]
Hi there! sorry for the late response ><

Firstly, I made a quick small mockup to be able to better explain what I meant regarding the link between UI & logo. I made this one just to show the very-round UI, but I can make modifications to this to showcase a 0 roundness version too. Also this is just for the Anime Info page, and once again, this is just a mockup, so the real version might not be closely related at all. 

![Mockup - 1](https://user-images.githubusercontent.com/41228366/160229332-814ac63e-964f-48ac-ba83-d5361eaa35aa.png)

Notice that all elements are very round, and so is the logo styling, so if I change the logo to be a sharp-cornered one, then the whole UI must adapt to that too. Same for the colors (I chose yellow on a whim to contrast the blue-black, but it can have several variations too; also there's the light mode-dark mode debate).

1. The project already looks pretty good! Of course, as with everything, it can get a lot better. Also, about icon packs - while I do know of other icon packs, I think it's best to modify/handcraft icons during the final phase of the project. That way, not only can we change them to be more rounded, we can also add tints/colors to them. It should be pretty easy to do for about 20-30 icons (which should be the average amount required).

2. Aha! I get it, the naming is very interesting! I think Core is a nice project name overall, and the decision to branch out the several sub-parts under the same name is also a great idea. Also, text logos for this should be pretty easy enough to make, and even, later on, _animate_.

3. Unfortunately, about storage providers there aren't any good ones I can recommend. I do know of kwik.cx (pahe's provider), but they have a invite system. And most of the others I know of are very much against copyrighted content, so... there's that. Sorry that I wasn't able to help.

ah also, the logo in the mockup is not of the final type or anything, I just made it to showcase the UI-logo links. 

Thank you, I'd love to be able to help!

Sorry again for the delay in responding~ wish you a great day ahead too!

**Comment by baseplate-admin** [comment]
I am worked on the anime info page. So now it looks like this 📦 

<details>
<summary>
With Episodes : 
</summary>

![1](https://user-images.githubusercontent.com/61817579/160236925-e8c49602-a506-4de7-ad2a-5e09b82e3ae0.PNG)

</details>
<details>
<summary>
Without Episodes : 
</summary>

![2](https://user-images.githubusercontent.com/61817579/160236936-4b82884d-847d-412c-bae7-b0349ed747b4.PNG)

</details>

Now lemme ask you some questions :P 

1. Do you think i should change the color from `#000000` to `#070519` ?
2. I like your design TBH. So i am going to add this part soon :) ![Inked160229332-814ac63e-964f-48ac-ba83-d5361eaa35aa_LI](https://user-images.githubusercontent.com/61817579/160237038-c4dd06b8-955b-4495-94da-167ec5d8d353.jpg)
3. I think more info here would be good dont you think ?![Inked160229332-814ac63e-964f-48ac-ba83-d5361eaa35aa_LI](https://user-images.githubusercontent.com/61817579/160237082-3fceb835-03e2-4ae4-9940-989426748e29.jpg)
4. What font did you use for your project ? I think it better suits the project. 
5. Please submit a pull request so your name shows up on this repo 🍡

**Comment by baseplate-admin** [comment]
Closing this in favor of #110

**Comment by baseplate-admin** [comment]
It seems i didnt read the last part

**Comment by AKindWorld** [comment]
Closing this for now, I'll upload some HQ logos once the UI redesign project is completed.
