### ISSUE TITLE
Home Page UI Redesign

### ISSUE THREAD

**Issue by AKindWorld** [baseplate-admin/CoreProject#115]
Current Progress - Completed, looking for feedback.

<details>
<summary>Full Vertical Mockup</summary>

![Link to Image](https://user-images.githubusercontent.com/41228366/160448618-4b9ce292-83a6-438a-bda0-6acf3d27bd76.png)
</details>

<details open>
<summary>Working Prototypes</summary><br>

1. [Homepage Top](https://www.figma.com/proto/knyOkHUChnJpsAsmuILhOk/Core-Project?page-id=0%3A1&node-id=80%3A51&viewport=241%2C48%2C0.49&scaling=scale-down&starting-point-node-id=76%3A5&show-proto-sidebar=1)
<br><br>
2. [Homepage Discover Section](https://www.figma.com/proto/knyOkHUChnJpsAsmuILhOk/Core-Project?page-id=0%3A1&node-id=129%3A12&viewport=241%2C48%2C0.49&scaling=scale-down&starting-point-node-id=129%3A12&show-proto-sidebar=1)
</details>

Mentions - Issue #110

**Comment by baseplate-admin** [comment]
Design looks good :)

**Comment by baseplate-admin** [comment]
But do you know which sliders did they use ?

**Comment by baseplate-admin** [comment]
Also do you know how to run a next.js server? To test some designs?

**Comment by baseplate-admin** [comment]
Take a look at this [codesandbox](https://codesandbox.io/s/swiper-mousewheel-control-react-forked-pygq40?file=%2Fsrc%2FApp.jsx). Tell me will this work ?

**Comment by AKindWorld** [comment]
>Also do you know how to run a next.js server? To test some designs?

I think I should be able to. I'll take a look at the docs.

>Take a look at this [codesandbox](https://codesandbox.io/s/swiper-mousewheel-control-react-forked-pygq40?file=%2Fsrc%2FApp.jsx). Tell me will this work ?

- **Homepage Top** - Yup, looks pretty good. Except that we possibly don't want it registering scroll-events, so it'll just be like a normal carousel/slideshow. Scroll can be implemented later on, but it's a huge UX flaw.

- **Homepage Discover** - Yup, this will absolutely work here. By making separate scrollers, we can also make a slick navigation.

Also, took a look at [SwiperJS](https://swiperjs.com/), and it should work amazing for what I wanted to incorporate. Good find!

>Along with [this](https://www.w3schools.com/css/tryit.asp?filename=trycss3_gradient-linear_trans#:~:text=%E2%80%8B%20%E2%80%8B%20%E2%80%8B-,Linear%20Gradient%20%2D%20Transparency,full%20color%20(no%20transparency).)

Yup, exactly the type of linear gradient I'd thought of. We need separate `div` fields for the image layer and gradient layer, possibly. At time there are multiple gradient layers. 

Talking about this, do you want me to add you a editor in the Figma file? That way, you can easily get the values of everything.

**Comment by baseplate-admin** [comment]
> Talking about this, do you want me to add you as a editor in the Figma file? That way, you can easily get the values of everything.

Sure, but i dont have a figma account. I will make one tonight :) . But i want to ask you something. Do you have any kind of social media to talk to ? Cause there are private matters that shouldn't exist in a public issue tracker.

**Comment by AKindWorld** [comment]
>Sure, but i dont have a figma account. I will make one tonight :)

Sure thing! Also, I just found out that Figma does not allow normal link-share editors anymore so the alternative is to create a new team and add members. I've already done that, but it displays the email addresses to everyone in the team. So, just wanted to let you know that. If you want to, feel free to sign up with a non-personal email.

>But i want to ask you something. Do you have any kind of social media to talk to ? Cause there are private matters that shouldn't exist in a public issue tracker.

I'm not on most of the traditional social media (Facebook, Twitter, Instagram) currently, but I do have a Discord account. Feel free to add me in there - `Titan#0415`. Also yup, you're right. A lot of these stuff are best discussed in private. Also I need to be able to send you the edit links too, which I can't in a public repo.

>Haha. I have more tools in my arsenal :)

xD. That's great, we'll need it sometime for sure!

**Comment by baseplate-admin** [comment]
> I'm not on most of the traditional social media (Facebook, Twitter, Instagram) 

Haha another match. I dont like either of those platform. I am a pretty anti facebook type guy.

>  If you want to, feel free to sign up with a non-personal email.

Though my mail is not allowed in public. It will be fine for that purpose. Gimme 5-6 hour to come home and tweak some stuff. But do check this project. https://relay.firefox.com It masks your email.

**Comment by AKindWorld** [comment]
Closing in favor of an upcoming issue/doc that explores and goes over the whole design system + all pages + UI components + mockups & docs.
