### ISSUE TITLE
[`Frontend`] : Deprecate `AnimeCore`

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#2269]

**Comment by baseplate-admin** [comment]
@tokitou-san,

We are open to discussions. What do you think is a better way to handle things ?

MPA  or SPA?

**Comment by tokitou-san** [comment]
> MPA or SPA?

SPA... boom! Svelte v5 would be a game changer.
and Idl MPA, if user has a bad internet connection MPA feels off.

and for MPA, you're planning to do with django templates, right?
then we need to host frontend along with backend, and if cant buy a good server ( speedy server )
it loads slow...
Hhh am I wrong?

**Comment by baseplate-admin** [comment]
Working with Microsoft PowerPoint

**Comment by tokitou-san** [comment]
> Now a days SPA is not strictly bound to JS. We can use things like HTMX and django to emulate SPA like feel.

Owwh, I dont know that.
I did an investigation on HTMX and Django and found this https://juliensalinas.com/en/htmx-intercoolerjs-django-nlpcloud/
This htmx and django combination lgtm, also it seems we need some tweaks in django.
Okay cool thing.

Do we need to migrate now?
Or we can do a great migration later.
But I'm sure, now or later migrating to django and htmx is a good thing.
Also I found this https://github.com/adamchainz/django-htmx, we use this?

**Comment by theetherGit** [comment]
As i can see you have django backed and as of now svelte as frontend, but serving static files from same server as your backend can end up having more static request. It's complete I/O based app, for serving large audience i'll support `SPA` with any framework. Having frontend on vercel or cloudflare make sense. 

For more better details we should think about our architecture for this. It's important to see things clearly.

**Comment by baseplate-admin** [comment]
Hi thanks for your valuable comment on this issue @theetherGit.


So let's start by answering some points.


The project is a monolith JamStack project.

>  serving static files from same server as your backend

We are not doing this approach.

So currently we serve the `svelte` project from `caddy` by reverse proxy-ing it

```mermaid
  graph TD;
      traffic-->caddy;
      caddy-->sveltekit;
      caddy-->django;
```

So essentially `django` and `sveltekit` are decoupled.

But this poses 2 major problems.

1. We can't use `python` for our application logics. Our backend developers are mostly experienced in python.
2. We can't use what `django` provides ( essentially we want to use `django`'s  to render HTML )

> Having frontend on vercel or cloudflare make sense


Correct. So that's why when we deploy the site we use 

```mermaid
  graph TD;
      traffic-->cloudflare;
      cloudflare-->vercel;
```

------

But `jamstack` has flaws. Most of our pages request far more data than they need. This increases the load on our server ( a bit ) and makes everything eat up more bandwidth than they need.


So essentially we are thinking of changing architecture to : 
* Have better integration between frontend and backend ( essentially use django's logic instead of creating our own )
* Have everything server rendered so there's no SEO problems ( SEO problems are a major headache of `SPA` applications )
* Reduce the data transfer between processes ( this can get expensive down the line )

**Comment by theetherGit** [comment]
@baseplate-admin Thanks for providing this overview.

> So currently we serve the svelte project from caddy by reverse proxy-ing it
> Correct. So that's why when we deploy the site we use

i think having caddy/nginx as reverse proxy is good for backend (Django) but for using it for sveltekit app is not what i'll go for. In this case where you mentioned using `vercel` & `cloudflare` together, you can change this to cloudflare pages or cloudflare workers (More efficient and better pricing). They provide better tooling and caching for a large project & dev experience is getting better (IK not best one).

> But jamstack has flaws. Most of our pages request far more data than they need. This increases the load on our server ( a bit ) and makes everything eat up more bandwidth than they need.

In this scenario, I think changing REST to `Graphql` or `grpc` like architecture is better approach if we need to limit data we send over the api. Django have good support for both, you can check them for future prospect. But both comes with a learning/understanding curve.

> Have better integration between frontend and backend ( essentially use django's logic instead of creating our own )
Agreed with this but can have different options.

>Have everything server rendered so there's no SEO problems ( SEO problems are a major headache of SPA applications )
That's why frameworks like SvelteKit, NextJs and NuxtJs exists. These framework solves SEO problems and make UI/UX experience much better.

>Reduce the data transfer between processes ( this can get expensive down the line)
If you can explain this furthur will be good.

> My architecture more something like this would be having `database` and `backend api` in one server with reverse proxy like `nginx/caddy`. Using api's with `sveltekit` or similar frameworks. `Backend API's` probably be `graphql` or you have big audience shift to `grpc` which solves data issue and other problems too. As of now you can write it in `django` and get more audience and you don't have a team scaling can be a problem for an instant. You should always keep in mind `IO` process for specific language. Because your project is heavy in `IO`. IDK about how you crawling data and all.

**Comment by baseplate-admin** [comment]
>  In this case where you mentioned using vercel & cloudflare together, you can change this to cloudflare pages or cloudflare workers (More efficient and better pricing).

That's the goal here, but due to how the project is, there's always a chance of getting DMCA in vercel/cloudflare. So that's why i have thought of hosting in our server.

>  I think changing REST to Graphql or grpc like architecture is better approach if we need to limit data we send over the api. 

That's the reason i opened : 
* # https://github.com/baseplate-admin/CoreProject/pull/2337


But the problem is with the graphql ecosystem. Django's graphql support is not upto par ( at least to build the site with all the features we require. I am stuck on the `user` authentication part for months  ) with `djangorestframework`. 

But yes i plan of visiting the PR soon ( after there's a bit more documentation on how to do things using `strawberry` )

**Comment by theetherGit** [comment]
> That's the goal here, but due to how the project is, there's always a chance of getting DMCA in vercel/cloudflare. So that's why i have thought of hosting in our server.
Even if you use your own server you will get that because you gonna use `cloudflare`. And for DMCA, user/owner have to report it same goes in every case.
> Because Cloudflare shares copyright infringement complaints with the relevant hosting providers and website operators, we only process reports that include all information required by section 512(c) of the DMCA.

> But the problem is with the graphql ecosystem. Django's graphql support is not upto par ( at least to build the site with all the features we require. I am stuck on the user authentication part for months ) with djangorestframework.

Let me see, i might have some thing on this but what kind of auth you are using `jwt` or `token`?
`djangorestframework` does save better support sometimes i think making your own doesn't hurt.
I think graphene used to have pretty good auth integration.

**Comment by baseplate-admin** [comment]
> i might have some thing on this but what kind of auth you are using jwt or token?

So i was actually using [`strawberry-django-auth`](https://github.com/nrbnlulu/strawberry-django-auth) for authenticating our users. But that library's documentation is lacking to say the least. I couldn't authenticate user using this library.

Now i am thinking of rolling our own `token` based authentication ( inspired by `django-rest-framework` )

>  I think graphene used to have pretty good auth integration.

The problem is from the lack of maintenance, that's why it's lacking behind in terms of feature and speed from `strawberry`

**Comment by theetherGit** [comment]
Ok, If you need any help with this you can ask me. Till then i'll work on MangaHour.

**Comment by baseplate-admin** [comment]
Course

**Comment by baseplate-admin** [comment]
> If you need any help with this you can ask me

Are you familiar with `token` auth in `strawberry`?

**Comment by theetherGit** [comment]
> Are you familiar with token auth in strawberry?

I haven't used `strawberry` but give a bit time i'll send a working example. Btw can you provide file link from github, I'll see that one first.

> MangaHour

Yes, new project. Not something like CoreProject just a side project and solving my own problems
- No signup
- No saving of data on server
- Tracking read history, bookmarks in Indexed DB(Browser): Only reason we usually read on same device and in same browser so we can do this.
- Some other problems too.
