### ISSUE TITLE
How can I build it?

### ISSUE THREAD

**Issue by longdaiquan** [baseplate-admin/CoreProject#2761]
Is the function of this project complete? Can I run it normally now? Is there a tutorial document or video?

**Comment by baseplate-admin** [comment]
Hi thanks for taking an interest in this project. 

Yes the project is complete, But we are unsatisfied with the approach svelte took. So we are planning on rewritting it. Currently i have semester final coming up. That's why the project is halted for a while

**Comment by longdaiquan** [comment]
> Hi thanks for taking an interest in this project.
> 
> Yes the project is complete, But we are unsatisfied with the approach svelte took. So we are planning on rewritting it. Currently i have semester final coming up. That's why the project is halted for a while

Do you have complete deployment documentation from previous projects? I like the UI interface you rewrote very much and look forward to completing it soon.

**Comment by longdaiquan** [comment]
Do you have complete deployment documentation from previous projects? I like the UI interface you rewrote very much and look forward to completing it soon.

**Comment by baseplate-admin** [comment]
>  I like the UI interface you rewrote very much and look forward to completing it soon.

The project will be completed in a week or two. @tokitouq  and i are working hand in hand to make this possible :D
