### ISSUE TITLE
[`Backend`] : Minor nitpicks

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#2876]
These files should be routed to their own files 

| Url | File Location |
| --- | ----------- |
| `https://127.0.0.1:8000/anime/explore` | https://github.com/baseplate-admin/CoreProject/blob/a3e4c4b107557f4602d398c504f30368bfeb13f0/backend/django_core/templates/anime/_partial_explore.html |
|  `https://127.0.0.1:8000/anime/1` | https://github.com/baseplate-admin/CoreProject/blob/a3e4c4b107557f4602d398c504f30368bfeb13f0/backend/django_core/templates/anime/_partial_info.html |

---

Export into own component : 
* https://github.com/baseplate-admin/CoreProject/blob/a3e4c4b107557f4602d398c504f30368bfeb13f0/backend/django_core/templates/anime/_layout.html#L119-L124

---

Remove ambiguous name : `<content/>` in places like : 
* https://github.com/baseplate-admin/CoreProject/blob/a3e4c4b107557f4602d398c504f30368bfeb13f0/backend/django_core/templates/user/register/index.html#L15
* https://github.com/baseplate-admin/CoreProject/blob/a3e4c4b107557f4602d398c504f30368bfeb13f0/backend/django_core/templates/user/register/_3.html#L35-L35
* https://github.com/baseplate-admin/CoreProject/blob/a3e4c4b107557f4602d398c504f30368bfeb13f0/backend/django_core/templates/user/register/_2.html#L51

We want `<content/>` to be something more generic `<user-content/>` maybe? That might help us to reduce clash down the line

**Comment by tokitouq** [comment]
> These files should be routed to their own files 

Okay you mean like this? looks good?
```
── anime
   ├── explore
      └── index.html
   ├── info
      └── index.html
   ├── index.html
   └── _layout.html
```
