### ISSUE TITLE
[ `Github` ] : Add social Template 

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#304]
So github can have a social template. @AKindWorld any plans to add support?

**Comment by baseplate-admin** [comment]
![Screenshot_20220604-094157_Firefox Nightly](https://user-images.githubusercontent.com/61817579/171980670-d9138366-7b4b-4aab-a419-3e7fac0e28f7.jpg)

**Comment by AKindWorld** [comment]
wow, this seems kinda nice xD

It may be a bit too much to ask for, but can you get an example for this one? I understand how it should look like, but doesn't Github also have a built-in dynamic social-media preview thing? @baseplate-admin 

Thanks!

**Comment by baseplate-admin** [comment]
> It may be a bit too much to ask for,

Not at all

> but can you get an example for this one?

![2ba60e80-c4c0-11eb-9de2-4c0929393732](https://user-images.githubusercontent.com/61817579/171981238-9fc2df1c-2a88-4c45-b878-359f7ac93ca3.png)

From https://github.com/marcreichel/igdb-laravel

**Comment by baseplate-admin** [comment]
The picture i sent you over at discord seems a good candidate :D

**Comment by AKindWorld** [comment]
Yep, thanks a lot!

Aha, just saw it. I'll resize and remodify it a bit, and then we can export and use it here :)

**Comment by baseplate-admin** [comment]
Thanks @AKindWorld 
As usual you rock

**Comment by baseplate-admin** [comment]
![unknown](https://user-images.githubusercontent.com/61817579/172052040-0b8ba03a-a120-4bdb-ac7c-e3f18d4ac674.png)
