### ISSUE TITLE
[ `Design` ] : Make better landing page.

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#308]
So the current landing page looks like this 

![image](https://user-images.githubusercontent.com/61817579/171987505-4d2b055e-5fd0-45e0-813c-8eeac746c22c.png)

maybe we can add some particles into the mix ?  
with [a cool js lib](https://vincentgarreau.com/particles.js/) ?

**Comment by baseplate-admin** [comment]
Pinging @AKindWorld

**Comment by AKindWorld** [comment]
> So the current landing page looks like this

Oh this is just the landing page for the Figma design file. For the project domain's landing page, I've got some pretty good better ideas xD

Just gimme a few more days for that.

> maybe we can add some particles into the mix ?
with [a cool js lib](https://vincentgarreau.com/particles.js/) ?

Yup, sounds good to me, I'll try to incorporate those.

Thanks & sorry for confusing you. @baseplate-admin

**Comment by baseplate-admin** [comment]
XD sorry i got confused. I thought this is a really good design. Thats why i wanted to make it a bit more cooler

**Comment by AKindWorld** [comment]
> XD sorry i got confused. I thought this is a really good design. Thats why i wanted to make it a bit more cooler

no worries :) 

But don't worry, our landing page should look something like this too, but better xD

**Comment by baseplate-admin** [comment]
Add all the sites that we have?

**Comment by baseplate-admin** [comment]
But not too bloated

**Comment by AKindWorld** [comment]
Hey @baseplate-admin!

I was working on something new, and decided to go over the Github Social banner and update it. 

Here's the final result - 

<img width="1280" alt="Github Social Template - FINAL v2" src="https://user-images.githubusercontent.com/41228366/181592200-55a61c0e-2718-4aea-ba90-2f2aa4826323.png">

Could you please update it? I did the last one in a hurry (and with an unfinished design system), so I wasn't too proud of it xD.

[Also sorry for barging this in the Landing page issue, but they're kinda related & I didn't want to open a new issue either]

Thanks!

^^

**Comment by baseplate-admin** [comment]
Done :D

**Comment by AKindWorld** [comment]
Yay, thanks! ^^

**Comment by baseplate-admin** [comment]
I like your design :D 


Good job :D

**Comment by baseplate-admin** [comment]
This is done
