### ISSUE TITLE
[ `Architecture` ] : `URLPatterns` Discussion

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#310]
## So the site operates like this ( we planned like this )

<details>

`https://example.com/animecore/`         ➜      `AnimeCore ( Static Files )`
`https://example.com/soundcore/`         ➜      `SoundCore ( Static Files )`
`https://example.com/api`                ➜      `API ( Django )`
`https://example.com/admin`              ➜      `Admin ( Django )` 
`https://example.com/faq`                ➜      `FAQ ( Django | Flatpages )` 

While they can be mapped to subdomain 

`https://example.com/animecore/`         ➜      `AnimeCore ( Node.js / Python http.server )`        ➜        `https://animecore.example.com/`
`https://example.com/soundcore/`         ➜      `SoundCore ( Node.js / Python http.server )`        ➜        `https://soundcore.example.com/`
`https://example.com/api`                ➜      `API ( Django )`                                    ➜        `https://api.example.com/`
`https://example.com/admin`              ➜      `Admin ( Django )`                                  ➜        `https://admin.example.com/`
`https://example.com/faq`                ➜      `FAQ ( Django | Flatpages )`                        ➜        `https://faq.example.com/`

</details>

## The Problem 

But this will break the immersion when the user switches pages from one app to another 

For example user from `https://soundcore.example.com` to `https://animecore.example.com` they will have to reload everything.

## So i am proposing that we do something like 

<details>

`https://example.com/animecore/`         ➜      `AnimeCore ( Static Files )`
`https://example.com/soundcore/`         ➜      `SoundCore ( Static Files )`
`https://example.com/api`                ➜      `API ( Django )`
`https://example.com/admin`              ➜      `Admin ( Django )` 
`https://example.com/faq`                ➜      `FAQ ( Django | Flatpages )` 

Instead of 

`https://animecore.example.com/`         ➜      `AnimeCore ( Node.js / Python http.server )`           
`https://soundcore.example.com/`         ➜      `SoundCore ( Node.js / Python http.server )`           
`https://api.example.com/`               ➜      `API ( Django )`                                       
`https://admin.example.com/`             ➜      `Admin ( Django )`                                     
`https://faq.example.com/`               ➜      `FAQ ( Django | Flatpages )`                           

</details>

**Comment by baseplate-admin** [comment]
@AKindWorld What do you think of this ?

**Comment by baseplate-admin** [comment]
While both can be achieved i am open to discuss this :)

**Comment by AKindWorld** [comment]
Hmm I see.

This isn't a big issue, but for this project, the domain names would become pretty long. So, in addition to this, what we can do is add a redirector like (which doesn't solve the long URL problem completely but could work)

* If the user types, `animecore.example.com` redirect to `example.com/animecore` by default.
* If the user types, `example.com/animecore`, we're all good.
* If the user types, `example.com/anime`, again redirect them to `example.com/animecore`

[Just an example. It could point to something else too.]

Once again, the only problem I see is very long URLs for our currently planned domain name & project names (~20 or >20 chars). 
What do you say? @baseplate-admin

**Comment by baseplate-admin** [comment]
Umm how can i tell exactly. Well i will explain it in Details after 6-7 hours.

**Comment by baseplate-admin** [comment]
> Once again, the only problem I see is very long URLs for our currently planned domain name & project names (~20 or >20 chars).
What do you say? @baseplate-admin

Sorry for the delay @AKindWorld 

So lemme explain whats happening.

`https://anime.example.com` <- This is a subdomain.
`https://example.com/anime` <- This is not a subdomain.

Now when you switch from domain to subdomain the SPA breaks. 

So this means if you do :
`https://example.com/anime` -> `https://example.com/manga` ( This is okay | The SPA experience wont break )

But if you do :
`https://anime.example.com/` -> `https://manga.example.com/` ( This is not okay | The Page will work as Multi Page Application ) 

If you need a refresher on SPA and MPA [check this post on discord that i sent you ](https://discord.com/channels/@me/958266195654639646/980104355216781383)

**Comment by baseplate-admin** [comment]
Also another thing 

✅ `https://anime.example.com/` 
❌ `https://animecore.example.com/`

**Comment by baseplate-admin** [comment]
> * If the user types, animecore.example.com redirect to example.com/animecore by default. 
   * If the user types, example.com/animecore, we're all good.
   * If the user types, example.com/anime, again redirect them to example.com/animecore


This part is honestly easy. Just add entry to the [`Caddyfile`](https://github.com/baseplate-admin/CoreProject/blob/c149409cc9c8e88a6f6e4f8c11f65e952103666d/Caddyfile)

**Comment by baseplate-admin** [comment]
@AKindWorld share some of your insights here too :D

**Comment by AKindWorld** [comment]
I think it's all good with this plan. @baseplate-admin 

So, the working URLs will be `example.com/anime`, `example.com/manga` and so on. (`anime` instead of `animecore`, works better)

Redirect all similar URLs to the ones above. That way, we get short URLs [<20 chars] + SPA does not break + Kokoro-chan happy :)
