### ISSUE TITLE
[`Frontend`] : Style comment section

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#3133]
| Status  | Location                                                                                                                                                              | Description                                                         | Image                                                                                                         |
| ------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------- |
| Done | https://github.com/baseplate-admin/CoreProject/blob/58b5158ed09869a9d5036b6450fe974005ef024a/backend/django_core/static_src/components/minor/Comment/Index.svelte#L89 | There should be some form of svg here. Not just a bland thing       |                                                                                                               |
| Done    | https://github.com/baseplate-admin/CoreProject/blob/58b5158ed09869a9d5036b6450fe974005ef024a/backend/django_core/static_src/components/minor/Comment/Index.svelte#L78 | There should be something svg related here, not just a loading text |                                                                                                               |
| Done | https://github.com/baseplate-admin/CoreProject/blob/58b5158ed09869a9d5036b6450fe974005ef024a/backend/django_core/static_src/components/minor/Comment/Index.svelte#L80 | Error state can be better explained                                 | ![image](https://github.com/baseplate-admin/CoreProject/assets/61817579/85342947-8b76-4a48-87df-a92920726d84) |

**Comment by tokitouq** [comment]
**All cases covered**
PRS:
#3153 
#3155 
#3141 
closing this**
