### ISSUE TITLE
[`Frontend`]: `image-loader` web-component

### ISSUE THREAD

**Issue by tokitouq** [baseplate-admin/CoreProject#3158]
Svelte implementation: https://github.com/tokitouq/v3-coreproject-ui/blob/master/src/lib/components/shared/image/image_loader.svelte

**Comment by baseplate-admin** [comment]
> Svelte implementation: https://github.com/tokitouq/v3-coreproject-ui/blob/master/src/lib/components/shared/image/image_loader.svelte

This is unnecessary, as we only will use this from svelte. Our normal apps cant use fetch anyways
