### ISSUE TITLE
[ `Architecture` ] : Tracker discussion.

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#355]
So in our current method we are doing a [fan out ](https://en.wikipedia.org/wiki/Fan-out_(software)) method to get all the trackers synced up.

This pattern is good if our application has a small userbase ( below 100k )

Because each service rate limits us at 90 req/min ( which effectively caps at 129,600 req/day

Now we have a few choices. We can either

1. Drop the server Fan Out method and switch to per application tracker sync ( this will make each interfaces more complicated )
2. Ask the service to increase our limits ( I donno if they will ever allow it )

So lets discuss this.

**Comment by baseplate-admin** [comment]
@AKindWorld give us some of your holy insights

**Comment by AKindWorld** [comment]
Holy insights xD

Hmm, but more seriously, I think we can go either of two ways for now - 

1. Keep the fan-out method for now, atleast until release and until we acquire a userbase, however small/large.
2. As you said, drop fan-out method & switch to something-else-more-complicated-that-goes-over-my-head.

The main factor here is how much work it is to switch to a different method later on. If it's not much work, we follow 1. If it's too much work, we follow 2. If it doesn't matter either way, we look at the other possible issues.

Of course, other factors are the database issues and all that stuff (if any); also yeah, I doubt that the 2nd way you mentioned will work - most services are very unlikely to increase our limits.

So, um- that's as far as I can say unfortunately :P

**Comment by baseplate-admin** [comment]
> The main factor here is how much work it is to switch to a different method later on. If it's not much work, we follow 1. If it's too much work, we follow 2. If it doesn't matter either way, we look at the other possible issues.

Its too much work ( that i am not familiar with | developing extensions is not me expertise )

> Of course, other factors are the database issues and all that stuff (if any); also yeah, I doubt that the 2nd way you mentioned will work - most services are very unlikely to increase our limits.

Thats what will happen i am afraid ( unless we become something big )
