### ISSUE TITLE
[ `Frontend` ] : Add font size 

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#363]
Pinging @AKindWorld 

You should define the pixels in [mantine theme object](https://mantine.dev/theming/extend-theme/#typography). :)

**Comment by baseplate-admin** [comment]
https://github.com/baseplate-admin/CoreProject/blob/8109250d8335449ba89e27d86c67f9a6ef96407b/frontend/AnimeCore/components/swiper/MainHero.tsx#L204

**Comment by AKindWorld** [comment]
> You should define the pixels in [mantine theme object](https://mantine.dev/theming/extend-theme/#typography). :)

wait- so there are other text scaling methods other than the headings h1-h6? That's great! How should I define them though? Just all the text sizes we'll use? or is there something else to mention too?

**Comment by baseplate-admin** [comment]
> wait- so there are other text scaling methods other than the headings h1-h6?

Yep

> That's great! How should I define them though?

Umm for starters gimme 6 different sizes for fonts. 

> Just all the text sizes we'll use? 

Yep (in pixels to be exact)

> or is there something else to mention too?

Nope 👀

**Comment by AKindWorld** [comment]
> Umm for starters gimme 6 different sizes for fonts.

Ah yeah, that's where the problem is - which 6 should I choose? I can give six for desktop, and six for mobile, but for both combined, it's pretty hard :/

That... or we can use em & rem, or font sizing in percentages to make it responsive, but I'm not sure if Mantine supports those.

**Comment by baseplate-admin** [comment]
> Ah yeah, that's where the problem is - which 6 should I choose? I can give six for desktop, and six for mobile, but for both combined, it's pretty hard :/

So lets do it like this : 

6 = Normal Button size for desktop
1 = Normal Button size for mobile

( 2-5 ) some random values.

**Comment by baseplate-admin** [comment]
But no worries if you cant get perfect sizing. I can always override stuff with CSS

**Comment by baseplate-admin** [comment]
> That... or we can use em & rem, or font sizing in percentages to make it responsive, but I'm not sure if Mantine supports those.

Anything that can be done in CSS can be done in mantine. But the time complexity increases and we might not have the uniform look that we are going for :P

**Comment by AKindWorld** [comment]
Okay, so 1-6 just for the Button sizing? That I can manage - but won't it cause problems in the other components?

> But no worries if you cant get perfect sizing. I can always override stuff with CSS

Oh I see. Well, I'll try to make out a good scale in a while - but yeah, I can guarantee a perfect one right now.

> Anything that can be done in CSS can be done in mantine. But the time complexity increases and we might not have the uniform look that we are going for :P

Ah I see! Yeah, well, using em & rem is a pretty time-taking task imo, so yeah - let's not try it, atleast now.

I'll work on the text scaling in a bit and send it here ^^

**Comment by baseplate-admin** [comment]
> Okay, so 1-6 just for the Button sizing? That I can manage - but won't it cause problems in the other components?

Actually lets do something different. I saw a different approach and we can check it tomorrow. For now lets make the change to the font size. Give me 6 font size that should cover both mobile and desktop ( i know this is hard but please take a look if you can do it )

 where 

6 = normal font size on desktop
1 = normal font size on mobile

(2-5) some random font size in between

**Comment by AKindWorld** [comment]
Alrighty I messed around a bit and I think this should work mostly for both mobile & desktop. If there's anything unincluded, then we can just use custom CSS for that part (there shouldn't be much though).

![image](https://user-images.githubusercontent.com/41228366/175815912-fd40bdab-d90e-445d-a236-24e03826da41.png)

Out of this, 24, 20 and 16 are the most used ones but all 6 are used in atleast 1 place throughout the whole project.

^^

**Comment by baseplate-admin** [comment]
Hey @AKindWorld would you mind closing this? I have ready used these variables 


----

Thanks ^_^
