### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#404]
So,

Yesterday my PC got busted. The USB  power delivery chip shorted for some reason. As the situation stands, i am without a PC. 

Now my PC is from 2016 with I5-7400 CPU. Motherboard for this CPU is scarce. In my city ( note that i am from a 3rd world country ). The motherboard is a relic.

So when I graduate from college ( which will happen in December this year ). I will be eligible for a new PC. Until then i wont be able to do coding 🙂

---

@AKindWorld Thanks for everything till now. I am glad i met you. Someday this site will be finished i hope. 

--- 

For anyone willing to contribute, i will still be here to answer questions.  

The backend is mostly complete. Its the Frontend that needs some work 

---
Thanks everyone.

**Comment by baseplate-admin** [comment]
![](https://ibb.co/fvQgKyF)

Here is a pic of my keyboard to show what i am facing

**Comment by baseplate-admin** [comment]
![20220705-102702](https://user-images.githubusercontent.com/61817579/177461461-966c34b2-7c8b-4adb-85d5-964bc0bdf862.jpg)

Here is a picture of my keyboard to show what problem i am facing

**Comment by AKindWorld** [comment]
oh my... I'm so sorry to hear that. Don't worry, I don't mind at all - there isn't anything you can do about this.

I'm really glad to have met you too - but we will continue on this project for sure. In the somewhat 6 months or so, I'll go ahead and work on my skills too. 

About maintainers, if there's anyone willing to step up, I'm all ready to help them with the designing too. If there isn't anyone, I'll be able to take care of this repo, but I can't contribute anything code-wise. The most I can do is update the Readme in a few days - it was actually due for an update.

Hope you get a cool new PC soon - and then we can work on this together again. 

Thank you, and wish you a great day ahead!

**Comment by baseplate-admin** [comment]
Hey tomorrow i am going to go to a shop to see if i can get my motherboard fixed :)

Lets hope i can get it fixed

**Comment by baseplate-admin** [comment]
Last update in https://github.com/baseplate-admin/CoreProject/pull/393#issuecomment-1179956059
