### ISSUE TITLE
[ `Frontend` ] : Add splash screen

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#419]
So we need a splash screen to reduce  `First Content Paint`.

A Blog post on this : https://blog.bitsrc.io/nextjs-splash-screen-7c8b528c69a2

**Comment by AKindWorld** [comment]
Going in through the blog link, I think we can use this one temporarily in our project. I was working to create a splash screen too, but I haven't yet figured out a good recurring logic of what to go by, except for animating simple shapes. I'll probably think and work on it later so for now, you can add this one.

https://uiverse.io/detail/mobinkakei/proud-ladybug-46 [just the circle version; centered]

and for the colors, use the following:
`--path: #DCD9F7;`
`--dot: #FF7081;`

and keep the splash screen background at `#212121`

Here's how it should look like: 

![](https://user-images.githubusercontent.com/41228366/180403750-0a7c23f8-c3dc-4aad-8f71-cf330d7dac82.gif)

I think adding a splash screen would be really great, and this one would look & fit in greatly too. Although I'm not sure about any technical constraints. Would this work? @baseplate-admin 

^^

**Comment by baseplate-admin** [comment]
hey there i have implemented this :D 

But svelte is so fast that i dont think users will see it 99% of the time.

Also i changed the background color ( i did it on black and i think it looks better ) 

Take a look :D 

^____^
