### ISSUE TITLE
[ `Design` ] : Anime Info page

### ISSUE THREAD

**Issue by AKindWorld** [baseplate-admin/CoreProject#438]
Mockups, design guidelines & Figma prototypes for the Anime Info page. 

Any feedback is welcome :)

^^

**Comment by baseplate-admin** [comment]
Lemme get back to you in 24 hours 👀

**Comment by AKindWorld** [comment]
**Redesign results - [Ongoing]** 

<details><summary>Old: </summary>


<br>

Laptop Layout:
![image](https://user-images.githubusercontent.com/41228366/181072670-f6b454b8-07c2-4ec0-9713-e7b2533c8bc8.png)

Desktop Layout: 
![image](https://user-images.githubusercontent.com/41228366/181072577-7ef8acc5-8bbe-434a-86e0-dc57fa87dc80.png)

Episode page Layout:
![image](https://user-images.githubusercontent.com/41228366/181072101-c4112486-3b0d-4147-8dc8-d60be89d052b.png)

</details>


<details open><summary>New: </summary>

<br>

Summary tab:
![image](https://user-images.githubusercontent.com/41228366/181072955-1cdd07a4-30ec-4db3-b593-8973c9caafa2.png)
 
Summary tab expanded: ![image](https://user-images.githubusercontent.com/41228366/181073119-fd8b3f51-15de-457b-8f18-9a0e07ea675e.png)

Episodes tab:
![image](https://user-images.githubusercontent.com/41228366/181073240-b62b11cf-7f63-4b54-a464-f494f01081ab.png)

Episodes tab expanded (scrollable):
![image](https://user-images.githubusercontent.com/41228366/181073874-874c1d5a-08c5-405b-9cd3-0662d13bf104.png)

[working on the others]

</details>

Advantages: 

1. One-page tabbed layout over Side tabs pagination.
2. Easier to navigate on large & small screens alike.
3. Essential utilities (Title, poster & watch buttons) remain on top.

Disadvantages:

1. Might have a contrast issue on the tabs layout - mainly makes it difficult for first time users (but I'll work on it).

Working prototype soon!

^^

**Comment by baseplate-admin** [comment]
Hi there,

@AKindWorld 


So take a look at this slide 
![image](https://user-images.githubusercontent.com/61817579/181305729-c2e013cc-dd0e-497c-a6f5-5a8402fc7d05.png)

Umm in my opinion theres too much spacing in the middle. Like cant we put the search box in the middle ? Also what does the icon here do?

**Comment by baseplate-admin** [comment]
hey i will be working on this next :D

**Comment by AKindWorld** [comment]
Heyo!

alrighty I worked a bit more on it, and now I have managed to solve almost all of the issues while having it synced to the design system.

<details>
<summary>Here's a few screenshots: </summary>

![image](https://user-images.githubusercontent.com/41228366/182404256-24bb068f-4d9d-4457-b358-bfa53487a664.png)

![image](https://user-images.githubusercontent.com/41228366/182404717-58390dcf-22a8-4d78-b003-846d23d34168.png)

![image](https://user-images.githubusercontent.com/41228366/182404802-d13d6f0e-01b7-49f2-990b-13f7376c7e74.png)


</details>

Issues solved:
1. Text contrast issue - now we have a cool background tint effect on scroll.
2. Start watching button more attractive - am working on it (the idea is done but I need to link the frames together).
3. Episode tab spacing issue - now we show essential information on there.
4. Tab contrast issue - changed colors and added 2px strokes for even more contrast.

**[>> Working prototype](https://www.figma.com/proto/tNUUtsk20ltOrQICdEoggG/Core-Project?page-id=587%3A1423&node-id=1607%3A4518&viewport=552%2C423%2C0.21&scaling=contain&starting-point-node-id=1607%3A4518&show-proto-sidebar=1)** 

unfortunately scroll events don't exist in Figma, so you have to drag the mouse up/down. In the real thing, this would be done by scroll, so it should be like: page loads on full viewport (onboarding)-> user scrolls (trigger) -> top shrinks, background darkens and the rest of the tab contents load (full contents) and then the user can scroll endlessly all the way till contents exist. Let me know if there's any problems with this method.

I'll make a separate comment detailing some of the parts soon.

^^

**Comment by baseplate-admin** [comment]
Got it.

Gimme some time :D 

In the mean time please take a look at https://github.com/baseplate-admin/CoreProject/pull/427#issuecomment-1202500249

**Comment by AKindWorld** [comment]
Hey, 

just a small heads-up: don't start working on this just yet - I got a different wave of ideas in my head, and am currently prototyping it (almost finished). The newer idea doesn't mess with animations and should be more stable in terms of performance.

if you already started on it, I'm really sorry for letting you know late.

I'll upload the prototype in a bit.

Good day to you ^^

**Comment by baseplate-admin** [comment]
> just a small heads-up: don't start working on this just yet - I got a different wave of ideas in my head, and am currently prototyping it (almost finished). The newer idea doesn't mess with animations and should be more stable in terms of performance.

No worries. I haven't started working on this page yet

**Comment by AKindWorld** [comment]
Hi hi!


<details>
<summary>Here's the full-height prototype: </summary>



![Anime Info Page v3 - 01](https://user-images.githubusercontent.com/41228366/184189317-443ebdeb-d394-46fe-aa95-81c0640e3a9f.png)

</details>

Pros: 
1. Everything in one scrollable page, with a simple layout (reduces scrolling/clicking too much).
2. No complex animations/pagination system - also reduces space wastage by a lot.
3. For smaller viewports, simply rearranging the right structures will suffice.
4. Makes it possible for the future - a feature where the user can hide/rearrange particular sections if they want to (not needed currently - but this layout makes it possible to use separate divisions for each sections). Also gives the user choice regarding what they want to expand/load instead of preloading all sections.

I'm working on the version containing all the data and will upload it soon ^^

**Comment by baseplate-admin** [comment]
As usual it Looks Awesome :D 

Awesome work :D 

One more request. Please send the data here too :) ( if its possible )

**Comment by baseplate-admin** [comment]
Also you forgot to add a con : 
1. It needs to be coded

**Comment by baseplate-admin** [comment]
@AKindWorld i have addressed some issues in discord. Take a look.

**Comment by baseplate-admin** [comment]
Hey @AKindWorld, 


Do you think prototype 4 is ready?

Cause i will start working on that :D
