### ISSUE TITLE
[ `Backend` ] : What are we looking for in forum

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#476]
Hey there,

I am currently merging [`MAL_Scraper`](https://github.com/baseplate-admin/MAL_Scraper) into [backend](https://github.com/baseplate-admin/CoreProject/blob/117bbf054dfd6fe952767f276de1348bee793c93/backend/apps/__anime__/management/commands/populate_characters.py). The integration is boring tbh but i have almost finished it.

---

So umm,

what kind of permissions are we looking for.

Are we looking for everything in reddit?

By that i mean:

1. User can post on forum
2. User can reply to forum post ( do we need commenting on forum items too ? )
3. Lock threads?

---

Also you should probably unsubscribe from #464 . There are too many notifications XD

cc @AKindWorld

**Comment by AKindWorld** [comment]
Hi! 

> what kind of permissions are we looking for.
> Are we looking for everything in reddit?

By permissions, do you mean the permissions that users have in the forums? 

If so, then yup - pretty much so, users can create, edit, vote and comments on posts & comments, and admins/moderators would have superuser perms, naturally - in my opinion.

> Also you should probably unsubscribe from https://github.com/baseplate-admin/CoreProject/pull/464 . There are too many notifications XD

Haha don't worry, I don't mind it at all xD

^^

**Comment by baseplate-admin** [comment]
> If so, then yup - pretty much so, users can create, edit, vote and comments on posts & comments, and admins/moderators would have superuser perms, naturally - in my opinion. 

Do we allow admin to delete posts on forum or using the django admin?

**Comment by AKindWorld** [comment]
> Do we allow admin to delete posts on forum or using the django admin?

I think being able to delete posts on forum would be the best course of way, but if it's hard/not possible, the other is possible too.
Anyways, it's okay even if we don't launch all features on release, we can slowly add them eventually, so don't overwork yourself :)

Primarily for a forum to function okay, all we need is the ability to create posts, comment on posts & reply to comments, and for admins to delete posts & comments. All of the extra stuff like editing posts & comments, locking threads, reporting, voting on posts & comments, etc can be created as we move on. So feel free to take your time on that.

^^

**Comment by baseplate-admin** [comment]
>  Anyways, it's okay even if we don't launch all features on release, we can slowly add them eventually, so don't overwork yourself :)

So what i am thinking is we are letting `giga-admins` use `django-admin` wheres `admins` use forum delete button to delete posts :P ( its just 3 lines of code. So not hard to implement this at all )

**Comment by AKindWorld** [comment]
> So what i am thinking is we are letting giga-admins use django-admin wheres admins use forum delete button to delete posts :P ( its just 3 lines of code. So not hard to implement this at all )

Sounds good to me :)

> So do we have reddit style tree based replies or [normal ](https://www.hoyolab.com/article/15501)replies

I think normal - kinda like the HoyoLab ones, so basically we're showing all comments to posts directly, and hide replies to comments behind another click-to-expand box.

> Also do we delete user posts when user deletes account

I think not- only if the user themselves deletes the post, will we delete them. Otherwise, posts made by a deleted user should stay with a Deleted User tag (you can make it system reserved), kinda like how Reddit deals with it (one way). If however, the user deletes both their posts and their account, then we'll delete both. We can provide a warning to the user when they're attempting to delete their account - something like "Posts created by you are not deleted even if you delete your account. If you want to delete all your posts as well, please delete the posts individually or apply for a mass deletion."

Btw, we're making a comment system in addition to the forum system, right? or is it just the forum system? or maybe we'll add Disqus for the comments and have the forum system self made? Which one do you think is best? Because I'll design the UI in that order.

Thanks! ^^

**Comment by baseplate-admin** [comment]
> Btw, we're making a comment system in addition to the forum system, right? or is it just the forum system? or maybe we'll add Disqus for the comments and have the forum system self made? Which one do you think is best? Because I'll design the UI in that order.

Umm i am still not sold on `Disqus`. But i have already coded the [comments](https://github.com/baseplate-admin/CoreProject/blob/6acd984d1434d5e5dbd18b178f533f82c19687fe/backend/apps/api/v1/anime/models/episode_comment.py) section. ( its simple | No tree style comments | do we need tree style comments ? )

**Comment by baseplate-admin** [comment]
> But we are making both a forum and a commenting system. Feel free to pick anything first. But for now since i am doing complete backend overhaul and i am also coding the discord bot :) We need a page to highlight discord bot stuff ( can you design that too? )

> So in this sense do we make a server with our project name? Cause i feel like that might help getting people to interact with us more directly ( and to test our bot for that matter )

Hi @AKindWorld ,

Should we take this to #305  ?

+~+

**Comment by AKindWorld** [comment]
Hi there! sorry for taking so long in responding back; I accidentally nuked my core drive while messing with some themes, and welp- ;-;

> Hmm but i prefer the reddit style ones because we can interact with users more directly that way. ( but lets go with your route | we can discuss this in future if needed :C )

I thought a bit more about it, imo here's what we can go with - 

<details>
<summary>tree-style comments for the comment section</summary>

![image](https://user-images.githubusercontent.com/41228366/185039034-841c7c75-4877-4935-b9ed-4538c39ebec4.png)

</details>
<details>
<summary>tree-style comments for the forums as well, but hidden/collapsed by default</summary>

![image](https://user-images.githubusercontent.com/41228366/185039095-66620238-a192-499c-b5c8-5b8eec72623e.png)

</details>

The collapsed/expanded part still requires more thinking - at most, we'll go with the same comment style for both, and that shouldn't be bad either.


> But we are making both a forum and a commenting system. Feel free to pick anything first. But for now since i am doing complete backend overhaul and i am also coding the discord bot :)

Aha sounds good to me.


> We need a page to highlight discord bot stuff ( can you design that too? )

Yup sure! I think a modal page would be a good option to use here, alongside more stuff (we'll see it as we move on)


> So in this sense do we make a server with our project name? Cause i feel like that might help getting people to interact with us more directly ( and to test our bot for that matter )

Sounds good to me, although I haven't been much active in Discord lately, but I think it would perhaps help a lot. Feel free to invite me when you're done creating it.


> Umm i am still not sold on Disqus. But i have already coded the [comments](https://github.com/baseplate-admin/CoreProject/blob/6acd984d1434d5e5dbd18b178f533f82c19687fe/backend/apps/api/v1/anime/models/episode_comment.py) section. ( its simple | No tree style comments | do we need tree style comments ? )

aha I see. As for the comment style, I think it would be best if we could have support for tree-style comments (as I attached that prototype on top), but if it's too much work, no worries.


> Sounds like a good way to get yourself trapped 💀

oh... um- I didn't mean it like that... maybe we can allow the user to mass-delete posts themselves? I thought it was too niche of a feature, so I wrote it that way. Tbh, we still don't know/have our userbase and count, so we can always expand on features later on.


> Should we take this to https://github.com/baseplate-admin/CoreProject/issues/305 ? or umm do you have any suggestions in this matter ?

For the Discord bot part, feel free to move it. We can continue with the forum/comment systems discussions here. And if you wanna close this, feel free to do that as well - we can create another one for when I design the Forum's UI.


Sorry for writing an picture-based encyclopedia in here :P

Good day to you ^^

**Comment by baseplate-admin** [comment]
> Hi there! sorry for taking so long in responding back; I accidentally nuked my core drive while messing with some themes, and welp- ;-;

Everything alright now ? I hope you recovered everything

> Yup sure! I think a modal page would be a good option to use here, alongside more stuff (we'll see it as we move on)

lets not make it overly complex. Just some stuff that our bot might benefit from. But first lets ask for what we are looking for in our bot

> aha I see. As for the comment style, I think it would be best if we could have support for tree-style comments (as I attached that prototype on top), but if it's too much work, no worries.

Yep i was coding for something like this. Only problem is i have no idea how to implement this ☠️ 

> oh... um- I didn't mean it like that... maybe we can allow the user to mass-delete posts themselves? I thought it was too niche of a feature, so I wrote it that way. Tbh, we still don't know/have our userbase and count, so we can always expand on features later on.

No worries. I was joking :P 

> For the Discord bot part, feel free to move it. We can continue with the forum/comment systems discussions here. And if you wanna close this, feel free to do that as well - we can create another one for when I design the Forum's UI.

So umm do we create our server ? Umm i sent you a DM a while back. ( don't worry it just says "Hi you there" ) to discuss how we should handle server creation. 

> For the Discord bot part, feel free to move it. We can continue with the forum/comment systems discussions here. And if you wanna close this, feel free to do that as well - we can create another one for when I design the Forum's UI.

Umm lets close it :D ( I will let you do the honors )

Thanks again for giving an detailed reply. Good day :D

**Comment by AKindWorld** [comment]
> Everything alright now ? I hope you recovered everything

Yup, thankfully - I save my files on separate drives, which were all safe. I just managed to corrupt my Windows installation, so I had to clean install everything; but it's better in one way - I managed to remove a lot of useless clutter; also it was my fault as well - I didn't backup a system restore image beforehand ;-;

> lets not make it overly complex. Just some stuff that our bot might benefit from. But first lets ask for what we are looking for in our bot

I think for now a bot that can link & find animes from their name is good enough. Later on, we can expand on the functionalities and have them linked to even greater details (like OPs, EDs, character infos, random recs).

> (tree-style comments for the comment section) sounds best.
Yep i was coding for something like this. Only problem is i have no idea how to implement this ☠️

ah oops- hope you'll be able to figure it out 

> No worries. I was joking :P But i am making this app in a way that it will scale to millions of user without hassle. Currently it can handle 18,000 requests per second.

That sounds pretty amazing to me!

> So umm do we create our server ? Umm i sent you a DM a while back. ( don't worry it just says "Hi you there" ) to discuss how we should handle server creation.

um sorry I missed your message ;-;

**Comment by AKindWorld** [comment]
> Umm lets close it :D ( I will let you do the honors )

alrighty, closing this issue :)

^^

**Comment by baseplate-admin** [comment]
> I think for now a bot that can link & find animes from their name is good enough. Later on, we can expand on the functionalities and have them linked to even greater details (like OPs, EDs, character infos, random recs).
 
 Adding this to backend is a bit tough 💀 . So many formats across so many website. We need to map the functionality ourself

> ah oops- hope you'll be able to figure it out

Some songs and a cola would help my brain 🤞🏻 

> That sounds pretty amazing to me!

Our site is read heavy. I can add varnish and it will scale to the moons ( hopefully )

> um sorry I missed your message ;-;

I sent you another message :)
