### ISSUE TITLE
[`Enhancement`] : Redesign Ui

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#778]
The last Redesign occurred at
* #420 

Now i think the new ui designed by @Akindworld looks fantastic.
I will start working on the UI. ( will probably take a while )

# Stack 
### Backend
* django
* django-ninja

### Frontend
Option 1 :
* svelte
* tailwindcss
* sveltekit

Option 2 :  ( i have a [branch  ](https://github.com/baseplate-admin/CoreProject/tree/react-new-mantine))
* react
* nextjs
* mantine

---

Figma file : https://www.figma.com/file/tNUUtsk20ltOrQICdEoggG/Core-Project?node-id=2052%3A2446

---

Any contribution is welcome 💪

**Comment by baseplate-admin** [comment]
https://github.com/mantinedev/mantine/discussions/1205

**Comment by baseplate-admin** [comment]
Work is underway.

We are using [skeleton UI](https://skeleton.dev)

**Comment by sssuneeth** [comment]
@baseplate-admin 
We still don't have enough v3 UI pages designs. That will be a problem soon.
