### ISSUE TITLE
The Site is not working 

### ISSUE THREAD

**Issue by alaniskhan** [baseplate-admin/CoreProject#93]
How can i connect the backend with the frontend

**Comment by baseplate-admin** [comment]
Hi there,

> How can i connect the backend with the frontend

This is a decoupled Frontend + Backend.  Meaning the Frontend and Backend lives on 2 server.

So the answer is

# For Backend :
```
 cd .\AnimeCore\backend\
 ```
 ```
 pipenv install --dev
 ```
 ```
 pipenv run dev
 ```
 
 # For Frontend :
 ```
 cd .\AnimeCore\frontend\
 ```
 ```
 npm install && npm run build && npm run preview
 ```

**Comment by baseplate-admin** [comment]
If you still can't understand how to do it. Would you like a video explaining on how i do it?

**Comment by alaniskhan** [comment]
> 

yeah pls do it

**Comment by baseplate-admin** [comment]
Sure. Wait a bit

**Comment by alaniskhan** [comment]
> If you still can't understand how to do it. Would you like a video explaining on how i do it?

yeah pls

**Comment by baseplate-admin** [comment]
Please do note the API is not stable :) . As i am still making the site. I am not responsible for api changes

**Comment by alaniskhan** [comment]
i have already runned the backend and frontend . but the anime i upload is not showing

**Comment by alaniskhan** [comment]
> Please do note the API is not stable :) . As i am still making the site. I am not responsible for Major API changes

ok

**Comment by alaniskhan** [comment]
> Sure. Wait a bit

ok i will wait

**Comment by baseplate-admin** [comment]
> i have already runned the backend and frontend . but the anime i upload is not showing

Actually that part is meant to be handled by django's admin panel

**Comment by baseplate-admin** [comment]
In case you cant run the `Server`

Heres a video showing how i run it :
https://send.vis.ee/download/cc3c666c9e626a4b/#FM6YhKMDynnigaU3S5SHlA

**Comment by baseplate-admin** [comment]
> i have already runned the backend and frontend . but the anime i upload is not showing

If you cant figure it out, 

Here's the way how i plan on uploading animes:
https://send.vis.ee/download/68e75f6d095509aa/#wEdToBYcth-qjD2TqQCc8w ( will expire in 7 days || 20 downloads )

You should have them over at `http://127.0.0.1:8000/api/v1/upload/anime/` after successful upload

**Comment by baseplate-admin** [comment]
Do note that the frontend doesn't pick up these uploaded files for now :(

I am working on this after i finish the capture endpoint to record timestamps :)

**Comment by baseplate-admin** [comment]
Anything more you want to ask?

**Comment by alaniskhan** [comment]
> Anything more you want to ask?

give me you WhatsApp number

**Comment by baseplate-admin** [comment]
> give me you WhatsApp number

Umm sadly i dont use any [`Facebook`](https://facebook.com) technologies. 

But i can give you my telegram. 


https://t.me/baseplate_admin

**Comment by baseplate-admin** [comment]
Do you have discord? 

I can also contact you over there :)

**Comment by alaniskhan** [comment]
> Do you have discord?
> 
> I can also contact you over there :)

yeah I have discord id Alanis Gaming#4973

**Comment by baseplate-admin** [comment]
Great. Msg me over there then
